config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get '/about' => 'public/homes#about', as: 'about'

  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root to: "homes#top"
  end

  namespace :public do
    resources :items, only: [:index, :show]
    get "search/items" => "items#search_item" ,as: "search_items"
    get "search/genre/:id" => "items#search_genre" ,as: "search_genre"
    resources :customers, only: [:confirm, :withdrawal]
    get "customers/mypage" => "customers#show", as: 'customer'
    get "customers/infomation/edit" => "customers#edit", as: 'customer_edit'
    patch "customers/infomation" => "customers#update", as: 'customer_update'
    get "customers/confirm" => "customers#confirm", as: 'customer_confirm'
    patch "customers/withdrawal" => "customers#withdrawal", as: 'customer_withdrawal'
    resources :addresses, except: [:new]
    post "orders/confirm" => "orders#confirm", as: 'order_confirm'
    get "orders/complete" => "orders#complete", as: 'order_complete'
    resources :orders, only: [:new, :create, :index, :show]
    delete "cart_items/destroy_all" => "cart_items#destroy_all", as: 'cart_items_destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer


  validates :post_code,:address,:name, presence: true
  validates :post_code, length: {minimum: 3}

  def address_display
  '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  validates :item_id, :amount, presence: true
  validates :amount, numericality:{ only_integer: true }
   
  def subtotal
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, uniqueness: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :item_image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_item_image
    (item_image.attached?) ? item_image : "no_image.jpg"
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.looks(words)
    @item = Item.where("name LIKE?", "%#{words}%")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum production_status:
        {
          impossible_production:0,
          waiting_production:1,
          producing:2,
          finish:3
        }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render "edit"
    end
  end

  private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
    @item = Item.new
    @genres = Genre.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private
   def item_params
     params.require(:item).permit(:name, :introduction, :price, :is_sale, :item_image, :genre_id)
   end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    update_production_status
    redirect_to request.referer
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

  def update_production_status
    if order_params[:status] == "confirm_payment"
      @order.order_details.update_all(production_status: 1)
    end
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10 offset-md-1 mb-5'>
      <div class="row m-5 align-items-center">
        <h2 class="bg-light">&nbsp;ジャンル編集&nbsp;</h2>
      </div>
      <div class="col-md-6 mx-auto">
        <%= form_with model:@genre, url: admin_genre_path, local:true do |f| %>
          <%= render 'layouts/errors', obj: @genre %>
          <div class="form-group">
            <%= f.label :ジャンル名 %>
            <%= f.text_field :name, placeholder: "ジャンル名", class: 'form-control genre_name' %>
          </div>
          <div class="form-group">
            <div class="mx-auto">
            <%= f.submit "変更を保存", class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-7 mb-5'>
      <div class="row m-5 align-items-center">
        <h2 class="bg-light">&nbsp;ジャンル一覧・追加&nbsp;</h2>
      </div>
      <div>
        <%= form_with model:@genre, url: admin_genres_path, local: true do |f| %>
          <%= render 'layouts/errors', obj: @genre %>
          <div class="form-group align-items-center">
            <table class="table table-borderless">
              <tr>
                <td><p class="font-weight-bold"><%= f.label :ジャンル名 %></p></td>
                <td><%= f.text_field :name, placeholder: "ジャンル名", class: 'genre_name' %></td>
                <td><%= f.submit "新規登録", class: 'btn btn-success' %></td>
              </tr>
            </table>
          </div>
        <% end %>
      </div>
    </div>
    <div class='col-md-6 mb-5'>
      <table class='table'>
        <thead class="bg-light">
          <tr>
            <th class="text-center">ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td class="text-center"><%= link_to "編集する", edit_admin_genre_path(genre), class: 'btn btn-success' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10 offset-md-1 mb-5'>
      <div class="row m-5 align-items-center">
        <h2 class="bg-light">&nbsp;商品編集&nbsp;</h2>
      </div>
      <div class="col-md-8 mx-auto">
        <%= form_with model:@item, url: admin_item_path, local:true do |f| %>
          <%= render 'layouts/errors', obj: @item %>
          <table class="table table-borderless">
            <tbody>
              <div class="form-group">
                <tr>
                  <td><%= f.label :商品画像 %></td>
                  <td><%= f.file_field :item_image, class: "form-control-image item_image", accept: 'image/*' %></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :商品名 %></td>
                  <td><%= f.text_field :name, placeholder: "商品名", class: 'form-control item_name' %></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :商品説明 %></td>
                  <td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: 'form-control item_introduction', rows: "10" %></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :ジャンル %></td>
                  <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {prompt: "選択してください"}, class: 'form-control item_genre' %></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :税抜き価格 %></td>
                  <td><%= f.text_field :price, placeholder: "1000", class: 'item_price' %><span>円</span></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :販売ステータス %></td>
                  <td>
                    <div class="form_check form-check-inline">
                      <%= f.radio_button :is_sale, true, class: "form-check-input item_is_sale" %>
                      <%= f.label :is_sale_true, "販売中" %>
                    </div>
                    <div class="form_check form-check-inline">
                      <%= f.radio_button :is_sale, false, class: "form-check-input item_is_sale" %>
                      <%= f.label :is_sale_false, "販売停止中" %>
                    </div>
                  </td>
                </tr>
              </div>
            </tbody>
          </table>
          <div class="form-group text-center">
            <tr>
              <td><%= f.submit "  変更を保存  ", class: 'btn btn-lg btn-success' %></td>
            </tr>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10 offset-md-1 mb-5'>
      <div class="row m-5 align-items-center">
        <h2 class="bg-light">&nbsp;商品一覧&nbsp;</h2>
        <div class="m-3 ml-auto">
          <%= link_to "＋", new_admin_item_path, class: "btn btn-light btn-lg rounded-circle p-3 shadow font-weight-bold", :style => "width:4rem; height:4rem;" %>
        </div>
      </div>
      <table class='table'>
        <thead class="bg-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody class="table-borderless">
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name,admin_item_path(item), :style => "color:black; text-decoration:underline" %></td>
              <td><%= item.price.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <% if item.is_sale == true %>
                <td class="text-success font-weight-bold"><%= "販売中" %></td>
              <% else %>
                <td class="text-secondary font-weight-bold"><%= "販売停止中" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row justify-content-center">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10 offset-md-1 mb-5'>
      <div class="row m-5 align-items-center">
        <h2 class="bg-light">&nbsp;新規商品登録&nbsp;</h2>
      </div>
      <div class="col-md-8 mx-auto">
        <%= form_with model:@item, url: admin_items_path, local: true do |f| %>
          <%= render 'layouts/errors', obj: @item %>
          <table class="table table-borderless">
            <tbody>
              <div class="form-group">
                <tr>
                  <td><%= f.label :商品画像 %></td>
                  <td><%= f.file_field :item_image, class: "form-control-image item_image", accept: 'image/*' %></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :商品名 %></td>
                  <td><%= f.text_field :name, placeholder: "商品名", class: 'form-control item_name' %></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :商品説明 %></td>
                  <td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: 'form-control item_introduction', rows: "10" %></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :ジャンル %></td>
                  <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {prompt: "選択してください"}, class: 'form-control item_genre' %></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :税抜き価格 %></td>
                  <td><%= f.text_field :price, placeholder: "1000", class: 'item_price' %><span>円</span></td>
                </tr>
              </div>
              <div class="form-group">
                <tr>
                  <td><%= f.label :販売ステータス %></td>
                  <td>
                    <div class="form_check form-check-inline">
                      <%= f.radio_button :is_sale, true, class: "form-check-input item_is_sale" %>
                      <%= f.label :is_sale_true, "販売中" %>
                    </div>
                    <div class="form_check form-check-inline">
                      <%= f.radio_button :is_sale, false, class: "form-check-input item_is_sale" %>
                      <%= f.label :is_sale_false, "販売停止中" %>
                    </div>
                  </td>
                </tr>
              </div>
            </tbody>
          </table>
          <div class="form-group text-center">
            <tr>
              <td class="text-center"><%= f.submit "  新規登録  ", class: 'btn btn-lg btn-success' %></td>
            </tr>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/search_genre.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10 offset-md-1 mb-5'>
      <div class="row m-5 align-items-center">
        <h2 class="bg-light">&nbsp;「<%= @genre.name %>」ジャンルの商品一覧&nbsp;</h2>
        <div class="m-3 ml-auto">
          <%= link_to "＋", new_admin_item_path, class: "btn btn-light btn-lg rounded-circle p-3 shadow font-weight-bold", :style => "width:4rem; height:4rem;" %>
        </div>
      </div>
      <table class='table'>
        <thead class="bg-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody class="table-borderless">
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name,admin_item_path(item), :style => "color:black; text-decoration:underline" %></td>
              <td><%= item.price.to_s(:delimited) %></td>
              <td><%= item.genre.name %></td>
              <% if item.is_sale == true %>
                <td class="text-success font-weight-bold"><%= "販売中" %></td>
              <% else %>
                <td class="text-secondary font-weight-bold"><%= "販売停止中" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row justify-content-center">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-10 offset-md-1'>
      <div class="row m-5 align-items-center">
        <h2 class="bg-light">&nbsp;商品詳細&nbsp;</h2>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-4">
            <%= image_tag @item.get_item_image, width: '100%' %>
          </div>
          <div class="col-8">
            <table class='table table-borderless'>
              <tr><th style="width: 30%">商品名</th><td><%= @item.name %></td></tr>
              <tr><th>商品説明</th><td><%= @item.introduction %></td></tr>
              <tr><th>ジャンル</th><td><%= @item.genre.name %></td></tr>
              <tr><th>税込み価格<br>(税抜き価格)</th><td class="align-middle"><%= ((@item.price * 1.1).floor).to_s(:delimited) %>&nbsp;(<%= @item.price.to_s(:delimited) %>)&nbsp;円</td></tr>
              <tr>
                <th>販売ステータス</th>
                <% if @item.is_sale == true %>
                  <td class="text-success font-weight-bold"><%= "販売中" %></td>
                <% else %>
                  <td class="text-secondary font-weight-bold"><%= "販売停止中" %></td>
                <% end %>
              </tr>
            </table>
          </div>
          <div class="mx-auto mb-5">
            <%= link_to "編集する", edit_admin_item_path, class: "btn btn-lg btn-success" %>
          </div>
        </div>
       </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container p-3">
  <div class="row">
    <div class="col-10">
      <h3 class="bg-light d-inline-block px-3 ml-5">注文履歴詳細</h3>
    </div>
    <div class="col-12">
      <%= form_with model: @order, url: admin_order_path do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th scope="col" style="width: 15%">購入者</th>
              <td scope="col" style="width: 70%"><%= @order.customer.last_name + @order.customer.first_name %></td>
            </tr>
            <tr>
              <th>注文日</th>
              <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
            <tr>
              <th>配送先</th>
              <td>
                〒<%= @order.post_code %>&nbsp;<%= @order.address %><br>
                <%= @order.name %>
              </td>
            </tr>
            <tr>
              <th>支払方法</th>
              <td><%= @order.payment_method_i18n %></td>
            </tr>
            <tr>
              <th>注文ステータス</th>
              <td>
                <%= f.select :status, Order.statuses_i18n.invert, {}, class: "px-2 py-1 mr-5 text-center" %>
                <%= f.submit "更新", class:"btn btn-success" %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class="col-9">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td align="center"><%= order_detail.purchase_price.to_s(:delimited) %></td>
            <td align="center"><%= order_detail.amount %></td>
            <td align="center"><%= (order_detail.purchase_price * order_detail.amount).to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f| %>
              <%= f.select :production_status, OrderDetail.production_statuses_i18n.invert, {}, class: "px-4 py-1 mr-3 text-center" %>
              <%= f.submit "更新", class:"btn btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3 position-relative">
      <table class="table table-borderless table-sm position-absolute" style="bottom: 0">
        <tr>
          <th>商品合計</th>
          <td align="right"><%= (@order.total_payment - @order.postage).to_s(:delimited) %>&nbsp;円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td align="right"><%= @order.postage.to_s(:delimited) %>&nbsp;円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td align="right"><strong><%= @order.total_payment.to_s(:delimited) %>&nbsp;円</strong></td>
        </tr>
      </table>
    </div>
  </div>
</div>