config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get '/about' => 'public/homes#about', as: 'about'

  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root to: "homes#top"
  end

  namespace :public do
    resources :items, only: [:index, :show]
    get "search/items" => "items#search_item" ,as: "search_items"
    get "search/genre/:id" => "items#search_genre" ,as: "search_genre"
    resources :customers, only: [:confirm, :withdrawal]
    get "customers/mypage" => "customers#show", as: 'customer'
    get "customers/infomation/edit" => "customers#edit", as: 'customer_edit'
    patch "customers/infomation" => "customers#update", as: 'customer_update'
    get "customers/confirm" => "customers#confirm", as: 'customer_confirm'
    patch "customers/withdrawal" => "customers#withdrawal", as: 'customer_withdrawal'
    resources :addresses, except: [:new]
    post "orders/confirm" => "orders#confirm", as: 'order_confirm'
    get "orders/complete" => "orders#complete", as: 'order_complete'
    resources :orders, only: [:new, :create, :index, :show]
    delete "cart_items/destroy_all" => "cart_items#destroy_all", as: 'cart_items_destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer


  validates :post_code,:address,:name, presence: true
  validates :post_code, length: {minimum: 3}

  def address_display
  '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  validates :item_id, :amount, presence: true
  validates :amount, numericality:{ only_integer: true }
   
  def subtotal
      item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, uniqueness: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_one_attached :item_image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def get_item_image
    (item_image.attached?) ? item_image : "no_image.jpg"
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def self.looks(words)
    @item = Item.where("name LIKE?", "%#{words}%")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum production_status:
        {
          impossible_production:0,
          waiting_production:1,
          producing:2,
          finish:3
        }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
    @item = Item.new
    @genres = Genre.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private
   def item_params
     params.require(:item).permit(:name, :introduction, :price, :is_sale, :item_image, :genre_id)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "") %> 件のエラーが発生しました:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_genre_search.html.erb
<table class="table table-borderless table-sm">
  <thead class="table-borderless">
    <tr class="border border-dark">
      <th class="text-center">ジャンル検索</th>
    </tr>
  </thead>

  <tbody class="border border-dark">
    <% genres.each do |genre| %>
      <tr>
        <td><%= link_to genre.name, public_search_genre_path(genre), :style => "color:black" %></td>
      </tr>
    <% end %>
    <tr><td><br></td></tr>
    <tr><td><br></td></tr>
    <tr><td><br></td></tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCakeEc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/4a9301fbb7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <header class="border-bottom border-dark">
      <div class="container-fluid">
        <div class="row">
          <div class="col-2 pl-5">
            <div class="logo">
              <%= link_to root_path, class: "lead" do %>
                <%= image_tag 'logo.png', :style => "max-height:120px" %>
              <% end %>
            </div>
          </div>
          <div class="col-3 offset-1 my-auto">
           <div class="text-center text-dark pb-3">
              <% if customer_signed_in? %>
                ようこそ、<%= current_customer.last_name %>さん！
              <% end %>
            </div>
          </div>
          <div class="col-6 pr-5">
            <nav class="navbar navbar-expand-md">
              <% if admin_signed_in? %>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item mr-3">
                    <%= link_to "商品一覧", admin_items_path, class: "nav-link text-white btn btn-outline-primary btn btn-secondary" %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to "会員一覧", admin_customers_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                </ul>
              <% elsif customer_signed_in? %>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item mr-3">
                    <%= link_to "マイページ", public_customer_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to "商品一覧", public_items_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to "カート", public_cart_items_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                </ul>
              <% else %>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item mr-3">
                    <%= link_to "About", about_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to "商品一覧", public_items_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to "新規登録", new_customer_registration_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_customer_session_path, class: "nav-link text-white btn btn-secondary" %>
                  </li>
                </ul>
              <% end %>
            </nav>
            <div class="float-right mt-3 pr-5">
              <div class="form-group row">
                <%= form_with url:public_search_items_path, method: :get, local: :true do |f| %>
                  <%= f.text_field :word, placeholder: "商品名を入力" %>
                  <%= f.submit "検索" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>

    <main>
      <div>
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>

    <footer class="text-center border-top border-dark">
      <div class="m-3">
        <p>CopyRight A4-danshi<A4男子></p>
      </div>
    </footer>
  </body>
</html>